[project]
name = "harness-wangz3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Manuel Magnabosco", email = "magn.manuel05@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dataclasses>=0.8",
    "typing>=3.10.0.0",
    "z3-solver>=5.1.0.0",
]

[project.scripts]
harness-wangz3 = "harness_wangz3:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
